### ISSUE TITLE
Should tokenizeShares fail if tx would cause validator to tokenize entire self bond?

### ISSUE THREAD

**Issue by joe-bowman** [iqlusioninc/liquidity-staking-module#38]
Found by a validator in the Quicksilver testnet:

The LSM currently permits a validator to tokenize their entire self-bond, which of course has the effect of removing them from the set with immediate effect. Should the LSM fail to tokenize shares in the event it would cause the self bond to fall below min_self_delegation?

**Comment by zmanian** [comment]
It's most likely that ADR-001 will be implemented and this will change the whole self bond behavior.
https://github.com/iqlusioninc/liquidity-staking-module/pull/37

**Comment by zmanian** [comment]
Otherwise I think it would be better to have the tokenization fail.

**Comment by joe-bowman** [comment]
This requirement is deprecated by #43
